name: Rust Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cargo lambda
        run: pip install cargo-lambda

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build and check vectordb_stuff
        run: |
          cargo build --release -p vectordb_stuff
          ls -hl target/release/vectordb_stuff
          cargo test -p vectordb_stuff
          cargo clippy -p vectordb_stuff

      - name: Build lambda_stuff
        run: |
          cargo lambda build --release -p lambda_stuff
          ls -hl target/lambda/lambda_stuff/bootstrap
          cargo clippy -p lambda_stuff
